<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class m_usahaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("m_usaha")->insert([
            [
                "code_mb" => "BM23070400001",
                "kd_usaha" => "US23070400001",
                "nama" => "KOPERASI KARYAWAN RANCABOLANG",
                "npwp" => "1234567899830010",
                "tahun" => "2021",
                "alamat" => " PERKEBUNAN RANCABOLANG ",
                "sektor" => "perdagangan",
                "produk" => "kahuripan",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "215000000",
                "jml_omzet" => "46000000",
                "laba_bersih" => "23000000",
                "jml_pekerja" => "5",
                "rencana" => "150000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400002",
                "kd_usaha" => "US23070400002",
                "nama" => "RENI PRIHANDINI",
                "npwp" => "1234567899840010",
                "tahun" => "2021",
                "alamat" => " BANDUNG ",
                "sektor" => "perdagangan",
                "produk" => "bawang goreng makjreng",
                "kap_produksi" => "50 pack/minggu",
                "ssr_usaha" => "marketplace",
                "jml_aset" => "150000000",
                "jml_omzet" => "40000000",
                "laba_bersih" => "20000000",
                "jml_pekerja" => "6",
                "rencana" => "150000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400003",
                "kd_usaha" => "US23070400003",
                "nama" => "SUBRAN KHOLID",
                "npwp" => "1234567899850010",
                "tahun" => "2021",
                "alamat" => " JALAN RAYA CILEUNYI NO.32 BANDUNG ",
                "sektor" => "perdagangan",
                "produk" => "teh seduh 88",
                "kap_produksi" => "100 pack/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "100000000",
                "jml_omzet" => "22000000",
                "laba_bersih" => "11000000",
                "jml_pekerja" => "10",
                "rencana" => "150000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400004",
                "kd_usaha" => "US23070400004",
                "nama" => "YAYAT HIDAYAT B",
                "npwp" => "1234567899860010",
                "tahun" => "2021",
                "alamat" => " JLN.PARAKANSAAT NO.17 RT06/06 KEC ARCAMANIK ENDAH ",
                "sektor" => "perdagangan",
                "produk" => "myeasah butik",
                "kap_produksi" => "50 item/bulan",
                "ssr_usaha" => "marketplace",
                "jml_aset" => "50000000",
                "jml_omzet" => "10000000",
                "laba_bersih" => "5000000",
                "jml_pekerja" => "3",
                "rencana" => "150000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400005",
                "kd_usaha" => "US23070400005",
                "nama" => "ASEP TASLAM NULKARIMAH",
                "npwp" => "1234567899870010",
                "tahun" => "2021",
                "alamat" => " JL SINDANG SIRNA BANDUNG ",
                "sektor" => "perdagangan",
                "produk" => "sabertooth",
                "kap_produksi" => "50 item/bulam",
                "ssr_usaha" => "marketplace",
                "jml_aset" => "50000000",
                "jml_omzet" => "8000000",
                "laba_bersih" => "4000000",
                "jml_pekerja" => "3",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400006",
                "kd_usaha" => "US23070400006",
                "nama" => "SITI MAHMUDAH",
                "npwp" => "1234567899880010",
                "tahun" => "2021",
                "alamat" => " JLN.MENGERGIRANG RT11 RW08 KEL.PASIRLUYU KEC.REGOL ",
                "sektor" => "perdagangan",
                "produk" => "serbamasker",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "102000000",
                "jml_omzet" => "15000000",
                "laba_bersih" => "7500000",
                "jml_pekerja" => "4",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400007",
                "kd_usaha" => "US23070400007",
                "nama" => "BEN IBRAHIM ABISUDJAK",
                "npwp" => "1234567899890010",
                "tahun" => "2021",
                "alamat" => " JL.ANTARIKSA NO 12 BANDUNG ",
                "sektor" => "perdagangan",
                "produk" => "girlsfashionstory",
                "kap_produksi" => "30 item/bulan",
                "ssr_usaha" => "marketplace",
                "jml_aset" => "50000000",
                "jml_omzet" => "9500000",
                "laba_bersih" => "4750000",
                "jml_pekerja" => "2",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400008",
                "kd_usaha" => "US23070400008",
                "nama" => "EUIS YULIANA",
                "npwp" => "1234567899900010",
                "tahun" => "2022",
                "alamat" => " KOPM. GBA 2 BLOK G5 RT10/09 CIPAGALO BJ SOANG BDG. ",
                "sektor" => "perdagangan",
                "produk" => "miya kitchen",
                "kap_produksi" => "100 item/minggu",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "220000000",
                "jml_omzet" => "62000000",
                "laba_bersih" => "31000000",
                "jml_pekerja" => "7",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400009",
                "kd_usaha" => "US23070400009",
                "nama" => "HENI HINDIYANA B",
                "npwp" => "1234567899910010",
                "tahun" => "2022",
                "alamat" => " JL.SAMPORA NO.282 DS.SUKAMENAK MARGAHAYU,BANDUNG ",
                "sektor" => "perdagangan",
                "produk" => "galeri store margahayu",
                "kap_produksi" => "10 kg susu/bln",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "30000000",
                "jml_omzet" => "10000000",
                "laba_bersih" => "5000000",
                "jml_pekerja" => "2",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400010",
                "kd_usaha" => "US23070400010",
                "nama" => "MUKTI MUHARAM B",
                "npwp" => "1234567899920010",
                "tahun" => "2022",
                "alamat" => " JL.SETRA INDAH BARAT 6 3/3 KEL.SUKAGIH, SUKAJADI ",
                "sektor" => "perdagangan",
                "produk" => "kebabest",
                "kap_produksi" => "50 kg/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "40000000",
                "jml_omzet" => "15000000",
                "laba_bersih" => "7500000",
                "jml_pekerja" => "4",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400011",
                "kd_usaha" => "US23070400011",
                "nama" => "SITI HALIDA B",
                "npwp" => "1234567899930010",
                "tahun" => "2022",
                "alamat" => " KOMP.GBA 2 BLOK G5 N0.23 KOTA BANDUNG ",
                "sektor" => "perdagangan",
                "produk" => "kripikenaku",
                "kap_produksi" => "40 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "25000000",
                "jml_omzet" => "5000000",
                "laba_bersih" => "2500000",
                "jml_pekerja" => "2",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400012",
                "kd_usaha" => "US23070400012",
                "nama" => "HENI H",
                "npwp" => "1234567899940010",
                "tahun" => "2022",
                "alamat" => " Jl. Cipaera No. 94/33 RT 01 RW 03 Kel. Malabar Kec. Lengkong Kota Bandung 40262 ",
                "sektor" => "jasa",
                "produk" => "jahit cantik",
                "kap_produksi" => "20 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "20000000",
                "jml_omzet" => "12000000",
                "laba_bersih" => "6000000",
                "jml_pekerja" => "3",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400013",
                "kd_usaha" => "US23070400013",
                "nama" => "ABDURRAHMAN WIDYA ANANTA",
                "npwp" => "1234567899950010",
                "tahun" => "2022",
                "alamat" => " HAURWANGIN RAJAMANDALA KAB.CIANJUR ",
                "sektor" => "jasa",
                "produk" => "jajanku",
                "kap_produksi" => "20 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "50000000",
                "jml_omzet" => "14000000",
                "laba_bersih" => "7000000",
                "jml_pekerja" => "3",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400014",
                "kd_usaha" => "US23070400014",
                "nama" => "RATNA KOMALA",
                "npwp" => "1234567899960010",
                "tahun" => "2022",
                "alamat" => " PERKEBUNAN PURBASARI PANGALENGAN ",
                "sektor" => "jasa",
                "produk" => "snekenak",
                "kap_produksi" => "20 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "50000000",
                "jml_omzet" => "10000000",
                "laba_bersih" => "5000000",
                "jml_pekerja" => "3",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400015",
                "kd_usaha" => "US23070400015",
                "nama" => "SURATMI",
                "npwp" => "1234567899970010",
                "tahun" => "2022",
                "alamat" => " KMP.BARUSULAM RT.92/RW.04 DESA SUKAMANAH ",
                "sektor" => "jasa",
                "produk" => "aulia tailor",
                "kap_produksi" => "20 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "50000000",
                "jml_omzet" => "11560000",
                "laba_bersih" => "5780000",
                "jml_pekerja" => "2",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400016",
                "kd_usaha" => "US23070400016",
                "nama" => "DEDE SUPRIATNA",
                "npwp" => "1234567899980010",
                "tahun" => "2022",
                "alamat" => " PERKEBUNAN PURBASARI PANGALENGAN ",
                "sektor" => "jasa",
                "produk" => "maisinimilk",
                "kap_produksi" => "20 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "50000000",
                "jml_omzet" => "9000000",
                "laba_bersih" => "4500000",
                "jml_pekerja" => "4",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400017",
                "kd_usaha" => "US23070400017",
                "nama" => "WAHYU",
                "npwp" => "1234567899990010",
                "tahun" => "2022",
                "alamat" => " PERKEBUNAN PURBASARI PANGALENGAN ",
                "sektor" => "jasa",
                "produk" => "meubel setra",
                "kap_produksi" => "20 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "250000000",
                "jml_omzet" => "50000000",
                "laba_bersih" => "25000000",
                "jml_pekerja" => "5",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400018",
                "kd_usaha" => "US23070400018",
                "nama" => "WINDIYANTI",
                "npwp" => "1234567900000010",
                "tahun" => "2022",
                "alamat" => " PERKEBUNAN PURBASARI ",
                "sektor" => "pertanian",
                "produk" => "pupuk organik 99",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "150000000",
                "jml_omzet" => "17000000",
                "laba_bersih" => "8500000",
                "jml_pekerja" => "4",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400019",
                "kd_usaha" => "US23070400019",
                "nama" => "JAJANG SUHENDAR",
                "npwp" => "1234567900010010",
                "tahun" => "2022",
                "alamat" => " PERKEBUNAN PURBASARI ",
                "sektor" => "pertanian",
                "produk" => "sentosa tani",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "134000000",
                "jml_omzet" => "14600000",
                "laba_bersih" => "7300000",
                "jml_pekerja" => "4",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400020",
                "kd_usaha" => "US23070400020",
                "nama" => "WIWI WINARSIH",
                "npwp" => "1234567900020010",
                "tahun" => "2022",
                "alamat" => " PERKEBUNAN PURBASARI ",
                "sektor" => "pertanian",
                "produk" => "tani utama",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "169000000",
                "jml_omzet" => "14000000",
                "laba_bersih" => "7000000",
                "jml_pekerja" => "4",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400021",
                "kd_usaha" => "US23070400021",
                "nama" => "DHIYA ULAYYA TSABITAH",
                "npwp" => "1234567900030010",
                "tahun" => "2022",
                "alamat" => " PERKEBUNAN PURBASARI ",
                "sektor" => "pertanian",
                "produk" => "asna tani",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "170000000",
                "jml_omzet" => "17000000",
                "laba_bersih" => "8500000",
                "jml_pekerja" => "4",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400022",
                "kd_usaha" => "US23070400022",
                "nama" => "MITRA KOLABORASI BRI",
                "npwp" => "1234567900040010",
                "tahun" => "2021",
                "alamat" => " PERKEBUNAN PURBASARI ",
                "sektor" => "pertanian",
                "produk" => "jaya tani",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "120000000",
                "jml_omzet" => "15000000",
                "laba_bersih" => "7500000",
                "jml_pekerja" => "4",
                "rencana" => "15000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 24,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400023",
                "kd_usaha" => "US23070400023",
                "nama" => "KELOMPOK H.MANSYUR",
                "npwp" => "1234567900050010",
                "tahun" => "2021",
                "alamat" => " PERKEBUNAN PURBASARI ",
                "sektor" => "pertanian",
                "produk" => "auika tani jaya",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "220000000",
                "jml_omzet" => "20000000",
                "laba_bersih" => "10000000",
                "jml_pekerja" => "4",
                "rencana" => "15000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 24,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400024",
                "kd_usaha" => "US23070400024",
                "nama" => "SULMID",
                "npwp" => "1234567900060010",
                "tahun" => "2021",
                "alamat" => " PERKEBUNAN PURBASARI ",
                "sektor" => "pertanian",
                "produk" => "kika tani",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "200000000",
                "jml_omzet" => "20000000",
                "laba_bersih" => "10000000",
                "jml_pekerja" => "4",
                "rencana" => "15000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 24,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400025",
                "kd_usaha" => "US23070400025",
                "nama" => "ASEP SOLEH",
                "npwp" => "1234567900070010",
                "tahun" => "2021",
                "alamat" => " PERKEBUNAN PURBASARI ",
                "sektor" => "perkebunan",
                "produk" => "Malikha Garden",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "167000000",
                "jml_omzet" => "10000000",
                "laba_bersih" => "5000000",
                "jml_pekerja" => "2",
                "rencana" => "15000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 24,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400026",
                "kd_usaha" => "US23070400026",
                "nama" => "SRIYANI",
                "npwp" => "1234567900080010",
                "tahun" => "2021",
                "alamat" => " Kp.Haurwangi RT.002 RW.005 Rajamandala ",
                "sektor" => "perkebunan",
                "produk" => "kamalia bakery",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "135000000",
                "jml_omzet" => "14000000",
                "laba_bersih" => "7000000",
                "jml_pekerja" => "3",
                "rencana" => "15000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 24,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400027",
                "kd_usaha" => "US23070400027",
                "nama" => "NINING SUNINGSIH",
                "npwp" => "1234567900090010",
                "tahun" => "2021",
                "alamat" => " KP BARUKAI PANYANDAAN ",
                "sektor" => "perkebunan",
                "produk" => "sayur hidroponik 77",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "50000000",
                "jml_omzet" => "10000000",
                "laba_bersih" => "5000000",
                "jml_pekerja" => "4",
                "rencana" => "15000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 24,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400028",
                "kd_usaha" => "US23070400028",
                "nama" => "AI ROKHAETI",
                "npwp" => "1234567900100010",
                "tahun" => "2021",
                "alamat" => " PERKEBUNAN JALUPANG ",
                "sektor" => "perkebunan",
                "produk" => "sayur semai",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "130000000",
                "jml_omzet" => "36000000",
                "laba_bersih" => "18000000",
                "jml_pekerja" => "10",
                "rencana" => "150000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400029",
                "kd_usaha" => "US23070400029",
                "nama" => "MUMUH",
                "npwp" => "1234567900110010",
                "tahun" => "2021",
                "alamat" => " MITRA KEBUN  TAMBAK SARI ",
                "sektor" => "perkebunan",
                "produk" => "Rumah Kaca Higenis",
                "kap_produksi" => "100 pcs/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "150000000",
                "jml_omzet" => "40000000",
                "laba_bersih" => "20000000",
                "jml_pekerja" => "5",
                "rencana" => "150000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400030",
                "kd_usaha" => "US23070400030",
                "nama" => "SURYATI",
                "npwp" => "1234567900120010",
                "tahun" => "2021",
                "alamat" => " MITRA KEBUN  TAMBAK SARI ",
                "sektor" => "industri",
                "produk" => "PT Intisari Industri",
                "kap_produksi" => "250 item/bulan",
                "ssr_usaha" => "antar provinsi",
                "jml_aset" => "100000000",
                "jml_omzet" => "22000000",
                "laba_bersih" => "11000000",
                "jml_pekerja" => "4",
                "rencana" => "150000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400031",
                "kd_usaha" => "US23070400031",
                "nama" => "E.AMINAH",
                "npwp" => "1234567900130010",
                "tahun" => "2021",
                "alamat" => " MITRA KEBUN  TAMBAK SARI ",
                "sektor" => "industri",
                "produk" => "PT Inti Boga Mandiri",
                "kap_produksi" => "250 item/bulan",
                "ssr_usaha" => "antar provinsi",
                "jml_aset" => "50000000",
                "jml_omzet" => "10000000",
                "laba_bersih" => "5000000",
                "jml_pekerja" => "2",
                "rencana" => "150000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400032",
                "kd_usaha" => "US23070400032",
                "nama" => "SUNARSIH",
                "npwp" => "1234567900140010",
                "tahun" => "2021",
                "alamat" => " MITRA KEBUN  TAMBAK SARI ",
                "sektor" => "industri",
                "produk" => "PT Gemilang Besari",
                "kap_produksi" => "250 item/bulan",
                "ssr_usaha" => "antar provinsi",
                "jml_aset" => "50000000",
                "jml_omzet" => "8000000",
                "laba_bersih" => "4000000",
                "jml_pekerja" => "2",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400033",
                "kd_usaha" => "US23070400033",
                "nama" => "SOLEH",
                "npwp" => "1234567900150010",
                "tahun" => "2022",
                "alamat" => " DESA KASOMALANG KEC JLN CAGAK ",
                "sektor" => "industri",
                "produk" => "PT Star Capcay ",
                "kap_produksi" => "250 item/bulan",
                "ssr_usaha" => "antar provinsi",
                "jml_aset" => "102000000",
                "jml_omzet" => "15000000",
                "laba_bersih" => "7500000",
                "jml_pekerja" => "4",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400034",
                "kd_usaha" => "US23070400034",
                "nama" => "YATI",
                "npwp" => "1234567900160010",
                "tahun" => "2022",
                "alamat" => " DESA KASOMALANG KEC JLN CAGAK ",
                "sektor" => "industri",
                "produk" => "PT Kiki Fresh Food",
                "kap_produksi" => "250 item/bulan",
                "ssr_usaha" => "antar provinsi",
                "jml_aset" => "50000000",
                "jml_omzet" => "9500000",
                "laba_bersih" => "4750000",
                "jml_pekerja" => "3",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400035",
                "kd_usaha" => "US23070400035",
                "nama" => "WATMI",
                "npwp" => "1234567900170010",
                "tahun" => "2022",
                "alamat" => " MITRA KEBUN  CIATER ",
                "sektor" => "jasa",
                "produk" => "hijabsmart",
                "kap_produksi" => "50 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "220000000",
                "jml_omzet" => "62000000",
                "laba_bersih" => "31000000",
                "jml_pekerja" => "6",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400036",
                "kd_usaha" => "US23070400036",
                "nama" => "LUKMAN",
                "npwp" => "1234567900180010",
                "tahun" => "2022",
                "alamat" => " MITRA KEBUN  CIATER ",
                "sektor" => "jasa",
                "produk" => "likaliku store",
                "kap_produksi" => "20 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "30000000",
                "jml_omzet" => "10000000",
                "laba_bersih" => "5000000",
                "jml_pekerja" => "3",
                "rencana" => "20000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400037",
                "kd_usaha" => "US23070400037",
                "nama" => "ATIN",
                "npwp" => "1234567900190010",
                "tahun" => "2022",
                "alamat" => " MITRA KEBUN  CIATER ",
                "sektor" => "jasa",
                "produk" => "sepatukuoke",
                "kap_produksi" => "20 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "40000000",
                "jml_omzet" => "15000000",
                "laba_bersih" => "7500000",
                "jml_pekerja" => "4",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400038",
                "kd_usaha" => "US23070400038",
                "nama" => "A.HARIS",
                "npwp" => "1234567900200010",
                "tahun" => "2022",
                "alamat" => " PERKEBUNAN CIATER ",
                "sektor" => "jasa",
                "produk" => "alinahijab",
                "kap_produksi" => "20 item/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "25000000",
                "jml_omzet" => "5000000",
                "laba_bersih" => "2500000",
                "jml_pekerja" => "2",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400039",
                "kd_usaha" => "US23070400039",
                "nama" => "WIWI",
                "npwp" => "1234567900210010",
                "tahun" => "2022",
                "alamat" => " DESA CIPANCAR KECAMATAN SAGALAHERANG ",
                "sektor" => "peternakan",
                "produk" => "domba ahli 99",
                "kap_produksi" => "50 kg/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "20000000",
                "jml_omzet" => "12000000",
                "laba_bersih" => "6000000",
                "jml_pekerja" => "4",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400040",
                "kd_usaha" => "US23070400040",
                "nama" => "ETI SUHARTINI",
                "npwp" => "1234567900220010",
                "tahun" => "2022",
                "alamat" => " DESA CIPANCAR III SAGALA HERANG ",
                "sektor" => "peternakan",
                "produk" => "sapi rezeki",
                "kap_produksi" => "50 kg/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "50000000",
                "jml_omzet" => "14000000",
                "laba_bersih" => "7000000",
                "jml_pekerja" => "4",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400041",
                "kd_usaha" => "US23070400041",
                "nama" => "TANTI ROSLIANTI",
                "npwp" => "1234567900230010",
                "tahun" => "2022",
                "alamat" => " KMP.SAKALI DESA CIKUJANG SAGALAHERANG ",
                "sektor" => "peternakan",
                "produk" => "sapi 77",
                "kap_produksi" => "50 kg/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "50000000",
                "jml_omzet" => "10000000",
                "laba_bersih" => "5000000",
                "jml_pekerja" => "4",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400042",
                "kd_usaha" => "US23070400042",
                "nama" => "L.ASWAT",
                "npwp" => "1234567900240010",
                "tahun" => "2022",
                "alamat" => " PERKEBUNAN CIATER SUBANG ",
                "sektor" => "peternakan",
                "produk" => "Daging Juara 78",
                "kap_produksi" => "50 kg/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "50000000",
                "jml_omzet" => "11560000",
                "laba_bersih" => "5780000",
                "jml_pekerja" => "3",
                "rencana" => "250000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400043",
                "kd_usaha" => "US23070400043",
                "nama" => "L.ARFAN",
                "npwp" => "1234567900250010",
                "tahun" => "2022",
                "alamat" => " KP.PASIRLANGU,KEC. CISARUA, KAB.BANDUNG BARAT ",
                "sektor" => "perikanan",
                "produk" => "lele berkah",
                "kap_produksi" => "20 kg/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "50000000",
                "jml_omzet" => "9000000",
                "laba_bersih" => "4500000",
                "jml_pekerja" => "3",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400044",
                "kd_usaha" => "US23070400044",
                "nama" => "L.SUMARNA",
                "npwp" => "1234567900260010",
                "tahun" => "2022",
                "alamat" => " KP.PASANGGRAHAN,DS.SINARJAYA,KEC.GUNUNGHALU,KBB ",
                "sektor" => "perikanan",
                "produk" => "ikan air tawar Arif",
                "kap_produksi" => "21 kg/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "250000000",
                "jml_omzet" => "50000000",
                "laba_bersih" => "25000000",
                "jml_pekerja" => "6",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400045",
                "kd_usaha" => "US23070400045",
                "nama" => "CHOIRUDDIN",
                "npwp" => "1234567900270010",
                "tahun" => "2022",
                "alamat" => " KP.BARU (TANGSI) DS.GN.HALU KEC.GN.HALU KAB.BARBAR ",
                "sektor" => "perikanan",
                "produk" => "Seafood Udin",
                "kap_produksi" => "22 kg/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "150000000",
                "jml_omzet" => "17000000",
                "laba_bersih" => "8500000",
                "jml_pekerja" => "3",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400046",
                "kd_usaha" => "US23070400046",
                "nama" => "ADI TJAHYONO",
                "npwp" => "1234567900280010",
                "tahun" => "2022",
                "alamat" => " KP.CIPOEK DS.SIRNAJAYA KEC. GUNUNG HALU KAB.BARBAR ",
                "sektor" => "perikanan",
                "produk" => "ikan cupang Sirnajaya",
                "kap_produksi" => "23 kg/bulan",
                "ssr_usaha" => "antar kabupaten",
                "jml_aset" => "134000000",
                "jml_omzet" => "14600000",
                "laba_bersih" => "7300000",
                "jml_pekerja" => "3",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400047",
                "kd_usaha" => "US23070400047",
                "nama" => "EKO SURYO",
                "npwp" => "1234567900290010",
                "tahun" => "2021",
                "alamat" => " PASIRLANGU RT.04/03 CISARUA, KAB.BANDUNG BARAT ",
                "sektor" => "perdagangan",
                "produk" => "lila sport",
                "kap_produksi" => "50 pcs/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "169000000",
                "jml_omzet" => "14000000",
                "laba_bersih" => "7000000",
                "jml_pekerja" => "3",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400048",
                "kd_usaha" => "US23070400048",
                "nama" => "SULAEMAN",
                "npwp" => "1234567900300010",
                "tahun" => "2021",
                "alamat" => " PARISLANGU RT.03/03 CISARUA, KAB.BANDUNG BARAT ",
                "sektor" => "perdagangan",
                "produk" => "Lavanya store",
                "kap_produksi" => "50 pcs/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "170000000",
                "jml_omzet" => "17000000",
                "laba_bersih" => "8500000",
                "jml_pekerja" => "3",
                "rencana" => "50000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400049",
                "kd_usaha" => "US23070400049",
                "nama" => "RIANTI RESA",
                "npwp" => "1234567900310010",
                "tahun" => "2021",
                "alamat" => " KARYAWANGI RT02/07,PARONGPONG KAB.BANDUNG BARAT ",
                "sektor" => "perdagangan",
                "produk" => "Restoran Mila",
                "kap_produksi" => "50 pcs/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "120000000",
                "jml_omzet" => "15000000",
                "laba_bersih" => "7500000",
                "jml_pekerja" => "2",
                "rencana" => "15000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "code_mb" => "BM23070400050",
                "kd_usaha" => "US23070400050",
                "nama" => "ANNISA RILANI",
                "npwp" => "1234567900320010",
                "tahun" => "2021",
                "alamat" => " PERKEBUNAN JALUPANG SUBANG ",
                "sektor" => "perdagangan",
                "produk" => "toko mikbad",
                "kap_produksi" => "50 pcs/bulan",
                "ssr_usaha" => "lokasi setempat",
                "jml_aset" => "220000000",
                "jml_omzet" => "20000000",
                "laba_bersih" => "10000000",
                "jml_pekerja" => "4",
                "rencana" => "15000000",
                "penggunaan" => "Bantuan Permodalan Usaha",
                "kesanggupan" => 36,
                "created_at" => now(),
                "updated_at" => now()
            ]
        ]);
    }
}
